print("olá,mundo!")
print("bem vindo!")
nome=input("qual é o seu nome? ")
print("olá,",nome," prazer em te conhecer!")
idade=input("qual é a sua idade? ")
cor=input("qual é a sua cor preferida? ")
animal=input("qual é o seu animal preferido? ")
print("a sua idade é",idade,", voce gosta da cor",cor,", e seu animal favorito é",animal,", correto?")